apiVersion: v2
name: acr-ui
description: A Helm chart for AppMarket Cost Report UI application
type: application
version: 0.1.0
appVersion: "0.0.1"
maintainers:
  - name: NHN AppMarket Team
keywords:
  - cost-report
  - ui
  - svelte
home: https://costreport.appmarket.nhn.no