apiVersion: v2
name: stats
description: A Helm chart for AppMarket Statistics UI application
type: application
version: 0.1.0
appVersion: "0.0.1"
maintainers:
  - name: NHN AppMarket Team
keywords:
  - cost-report
  - ui
  - react
home: https://stats.appmarket.nhn.no