version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=stats123
      - POSTGRES_USER=stats123
      - POSTGRES_DB=stats
