apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sync-ror-secret
  namespace: am-stats
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: sync-ror-secret
    creationPolicy: Owner
  data:
    - secretKey: ROR_API_KEY
      remoteRef:
        metadataPolicy: Fetch
        key: ror-api
        property: api_key