apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: stats
  name: stats-initdb
spec:
  instances: 3
  bootstrap:
    initdb:
      database: stats
      owner: stats
  storage:
    size: 20Gi

