apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: robot-secret
  namespace: stats
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: robot-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ncr.sky.nhn.no":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: keys
        property: harbor-robot-user
    - secretKey: password
      remoteRef:
        key: keys
        property: harbor-robot-key