apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: robot-secret
  namespace: stats
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: robot-secret
    creationPolicy: Owner
  data:
    - secretKey: HARBOR-ROBOT-KEY
      remoteRef:
        key: keys
        property: harbor-robot-key