apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: stats
spec:
  provider:
    vault:
      server: "https://openbao.test.nhn.no"
      namespace: "am-stats"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "k8s-role"
          serviceAccountRef:
            name: vault-auth